# Generated by Django 2.2 on 2019-10-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_store', '0005_auto_20191003_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
