# Generated by Django 2.2 on 2019-09-26 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Theme Title')),
                ('description', models.CharField(max_length=300, verbose_name='Theme Description')),
                ('image_url', models.CharField(max_length=30, verbose_name='Theme Image Url')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="User's Name")),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Theme Score')),
                ('comment', models.CharField(max_length=300, verbose_name='Review Comment')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_store.Theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_store.User')),
            ],
        ),
    ]
