# Generated by Django 2.2 on 2019-09-26 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Template Title')),
                ('description', models.CharField(max_length=300, verbose_name='Template Description')),
                ('image_url', models.CharField(max_length=30, verbose_name='Template Image Url')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='theme',
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.FloatField(verbose_name='Score'),
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AddField(
            model_name='review',
            name='template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='template_store.Template'),
        ),
    ]
