# Generated by Django 2.2 on 2019-09-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_store', '0002_auto_20190926_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(default=None, max_length=30, verbose_name='Review Title'),
        ),
        migrations.AlterField(
            model_name='template',
            name='image_url',
            field=models.CharField(max_length=300, verbose_name='Template Image Url'),
        ),
    ]
