# Generated by Django 2.2 on 2019-09-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_store', '0003_auto_20190926_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='color',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='Template Color'),
        ),
    ]
